name: Lint and Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
          
      - name: Check out into the root
        uses: actions/checkout@v2

      - name: Run Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

      - name: Run Vet
        run: go vet

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: Check out into the root
        uses: actions/checkout@v2

      - name: Test
        run: go test -v ./... -cover -covermode=atomic
